runtime: python39  # 使用 Python 3.9 运行时

instance_class: F2  # 选择实例类，可以根据需要调整

env_variables:  # 设置环境变量
  HOSTNAME: "34.129.71.70"
  PORT: "3306"
  USERNAME: "root"
  PASSWORD: "123456"
  DATABASE: "farmbotdata"
  SECRET_KEY: "123456"

automatic_scaling:  # 自动缩放的配置，可以根据需要调整
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: gunicorn -b :$PORT main:app  # 指定入口点，其中 main 是你的主 Python 文件名，app 是 Flask 应用实例

