runtime: python39  # 你可以根据你的需要选择 Python 的版本
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10  # 你可以根据你的需要调整这些参数

entrypoint: gunicorn -b :$PORT app:app  # 这里假设你的 Flask app 对象的名字是 'app'

env_variables:
  SECRET_KEY: "your-secret-key"  # 你可以设置环境变量

runtime_config:
  python_version: 3
